# Run 1 : Baseline

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

### Chargement des données d'apprentissage et de test

In [9]:
df_train = pd.read_csv("../data/train.csv", sep=',', encoding='utf-8')
df_validation = pd.read_csv("../data/validation.csv", sep=',', encoding='utf-8')
df_test = pd.read_csv("../data/test.csv", sep=',', encoding='utf-8')

### Prédiction de manière aléatoire

In [ ]:
x = df_train[['titre', 'ingredients','recette']]
y = df_train["type"]

x_test = df_test[['titre', 'ingredients','recette']]
y_test = df_test["type"]

y_pred = np.random.choice(y, size=len(x_test))

#### Résultats

In [15]:
score = accuracy_score(y_pred,y_test)
print("Accuracy:", score, "\n")
print(classification_report(y_test, y_pred), "\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.3472622478386167 

                precision    recall  f1-score   support

       Dessert       0.28      0.30      0.29       407
        Entrée       0.22      0.23      0.23       337
Plat principal       0.47      0.44      0.45       644

      accuracy                           0.35      1388
     macro avg       0.32      0.32      0.32      1388
  weighted avg       0.35      0.35      0.35      1388
 

[[123 115 169]
 [106  77 154]
 [207 155 282]]
