# Run 1 : Baseline

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

### Chargement des données d'apprentissage et de test

In [3]:
df_train = pd.read_csv("../data/train.csv", sep=',', encoding='utf-8')
df_validation = pd.read_csv("../data/validation.csv", sep=',', encoding='utf-8')
df_test = pd.read_csv("../data/test.csv", sep=',', encoding='utf-8')

### Prédiction de manière aléatoire

In [4]:
x = df_train[['titre', 'ingredients','recette']]
y = df_train["type"]

x_test = df_test[['titre', 'ingredients','recette']]
y_test = df_test["type"]

y_pred = np.random.choice(y, size=len(x_test))

#### Résultats

In [5]:
score = accuracy_score(y_pred,y_test)
print("Accuracy:", score, "\n")
print(classification_report(y_test, y_pred), "\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.3760806916426513 

                precision    recall  f1-score   support

       Dessert       0.30      0.31      0.31       407
        Entrée       0.23      0.22      0.23       337
Plat principal       0.49      0.50      0.50       644

      accuracy                           0.38      1388
     macro avg       0.34      0.34      0.34      1388
  weighted avg       0.37      0.38      0.37      1388
 

[[126 104 177]
 [105  74 158]
 [183 139 322]]
